#!/bin/sh
# Give a battery name (Check the battery name from sys/class/power_supply/ e.g. BAT0 or BAT1 and pass it as an argument.

case $BLOCK_BUTTON in
    3) pgrep -x dunst >/dev/null && notify-send "🔋 Battery module" "🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!
- Text color reflects charge left" ;;
esac

battery="/sys/class/power_supply/BAT1"
capacity=$(cat "$battery"/capacity) || exit
status=$(cat "$battery"/status)
left=$(acpi | awk '{print $5}')

if [ "$capacity" -le 35 ] && [ "$status" = "Discharging" ]; then
	# color="#ff0000"
	warn="❗"
	notify-send "$warn$status Battery Low"
fi

printf "%s%s%s%s\n" "$(echo "$status" | sed "s/,//;s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/ﮣ/;s/Unknown/♻️/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')" " $(echo "$left")"

# oneliner without warnings
# acpi | awk '{print $3$4$5}' | sed "s/,//;s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/ﮣ/;s/Unknown/♻<fe0f>/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g;s/,/ /g"
