#!/bin/sh

case $BLOCK_BUTTON in
        1) setsid "$TERMINAL" -e newsboat ;;
	2) setsid newsup >/dev/null & exit ;;
esac

cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ if($1>0) print "📰" $1}')$(cat "${XDG_CONFIG_HOME:-$HOME/.config}"/newsboat/.update 2>/dev/null)"
# NNEWS=$(cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ print $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)")
# [ -z "$NNESW" ] && printf "%s" "$NNEWS"
